# Kafka installation using Bitnami Helm chart
# This helps you learn Helm chart installation and configuration

apiVersion: v1
kind: Namespace
metadata:
  name: kafka
  labels:
    name: kafka
---
# TODO: Add HelmRelease for GitOps deployment
# This helps you learn GitOps patterns with Flux or ArgoCD
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: kafka
#   namespace: kafka
# spec:
#   interval: 5m
#   chart:
#     spec:
#       chart: kafka
#       version: 19.x.x
#       sourceRef:
#         kind: HelmRepository
#         name: bitnami
#         namespace: flux-system
#   values:
#     replicaCount: 1
#     persistence:
#       enabled: true
#       size: 8Gi
#     metrics:
#       enabled: true
#       serviceMonitor:
#         enabled: true

# TODO: Add Kafka configuration for production
# This helps you learn Kafka production configurations
#     config:
#       auto.create.topics.enable: "true"
#       log.retention.hours: "168"
#       log.segment.bytes: "1073741824"
#       num.partitions: "3"
#       default.replication.factor: "1"

# TODO: Add security configurations
# This helps you learn Kafka security best practices
#     auth:
#       clientProtocol: plaintext
#       interBrokerProtocol: plaintext
#       tls:
#         enabled: false
#         autoGenerated: false 