{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "consumer.serviceAccountName" . }}
  labels:
    {{- include "consumer.labels" . | nindent 4 }}
  # TODO: Add service account annotations for IAM roles (if using AWS/GCP)
  # This helps you learn cloud provider integration patterns
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT:role/ROLE_NAME
{{- end }} 