{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "producer.serviceAccountName" . }}
  labels:
    {{- include "producer.labels" . | nindent 4 }}
  # TODO: Add annotations for service account
  # This helps you learn RBAC and security patterns
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }} 