apiVersion: v1
kind: Service
metadata:
  name: {{ include "producer.fullname" . }}
  labels:
    {{- include "producer.labels" . | nindent 4 }}
  # TODO: Add annotations for service mesh integration
  # This helps you learn service mesh patterns
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "producer.selectorLabels" . | nindent 4 }} 